# Numpy

## arange

In [1]:
import numpy as np

In [5]:
a=np.arange(6) # 0~5까지
a #1차원 형태

array([0, 1, 2, 3, 4, 5])

In [7]:
a2=a[np.newaxis,:] #2차원으로
a2

array([[0, 1, 2, 3, 4, 5]])

In [9]:
a.shape, a2.shape

((6,), (1, 6))

## array

In [11]:
b_list=[0,1,2,3]
b=np.array(b_list)
b

array([0, 1, 2, 3])

In [13]:
a=np.array([1,2,3,4,5,6]) #리스트의 형태로 집어넣음
a

array([1, 2, 3, 4, 5, 6])

In [16]:
a=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]]) #리스트 안에 여러 리스트로 2차원 형태
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

## 인덱싱

In [19]:
a[0] #[,]아니면 행으로 가지고 옴

array([1, 2, 3, 4])

In [18]:
a[:,2]

array([3, 5, 7])

In [20]:
a[2,3]

8

## array와 list의 차이

In [12]:
# 리스트와 넘파이array의 차이
c_list=[0,'1',2.0,3]
c=np.array(c_list)
print(c_list) #다른 종류끼리 가능
print(c)  #다 같은 종류가 됨

[0, '1', 2.0, 3]
['0' '1' '2.0' '3']


In [ ]:
a=np.array()