# ndarray-n차원 배열
1-D는 vector  
2-D는 matrix  
3-D이상은 tensor  
차원은 axes라고 함

# 1.배열 만들기
np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [1]:
import numpy as np

### np.array(object,dtype,*,copy,order)

In [4]:
a=np.array([1,2,3]) #1차원이면 행만있는 형태(가로로)
print(a.shape)
a

(3,)


array([1, 2, 3])

In [54]:
b=np.array([[1,2,3]]) #가로2개면 2차원 형태
b, b.shape

(array([[1, 2, 3]]), (1, 3))

### np.zeros(shape,dtype,order)

In [3]:
# 0으로 채워진 배열
z=np.zeros(4)
z

array([0., 0., 0., 0.])

In [4]:
z.shape

(4,)

In [7]:
np.zeros([2,3]) #안에 리스트 넣어 2행 3열로

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones(shape,dtype,order)

In [6]:
# 1로 채워진 배열
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.empty(shape,dtype,order)

In [12]:
# 임의로 값 넣기
np.empty(20)

array([ 1.17130813e-311,  5.82997462e-322,  0.00000000e+000,
        0.00000000e+000,  8.01097888e-307,  1.16095484e-028,
        1.33733649e+160,  8.12555790e-096,  5.41236181e-072,
       -1.55011805e-164, -1.82019278e-262, -4.58435119e-256,
       -2.57832455e-171, -2.35329437e+210,  8.82142681e+199,
        1.71872049e+161,  4.30259873e-096,  9.80058441e+252,
        1.23971686e+224,  6.80144762e-310])

In [13]:
np.empty([3,5])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.29178686e-312]])

### np.arange(start,end,step,dtype)

In [19]:
np.arange(4) #처음에서 끝-1까지

array([0, 1, 2, 3])

In [16]:
np.arange(1,35,3) #3씩 띄고

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34])

### np.linspace(start,stop,num)

In [18]:
#선형으로 시작에서 끝까지+ 개수지정
np.linspace(0,10,num=7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [20]:
#배열의 데이터 타입 지정
np.ones([2,3],dtype=np.int64)  #각 요소들은 int64형태

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

### 속도 측정
%timeit

In [21]:
%timeit np.ones(5) #무수히 많이 실행해서 평균 속도 측정

864 ns ± 17.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# 2. 정렬

## 정렬
np.sort(), np.argsort(), np.lexsort(), np.searchsorted(), np.partition()

## np.sort(axis=-1,kind,order)
축, 종류, 순서를 지정하여 정렬

In [22]:
arr=np.array([2,1,5,3,7,4,6,8])

In [23]:
np.sort(arr) #기본적으로 작은 수 부터 큰수로

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#역순 정렬(sort함수에 기능 없음)
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [30]:
np.random.seed(1)
a=np.random.randint(0,10,12) #0~10까지 중 랜덤하게 12개 가져와 배열로

In [29]:
np.sort(a)

array([0, 0, 1, 2, 4, 5, 5, 6, 7, 8, 9, 9])

### 2차원 이상 정렬

In [32]:
a=a.reshape(3,4) # .reshape([3,4])도 가능
a

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [34]:
np.sort(a) #기본 axis=-1이어서 행끼리 정렬

array([[5, 5, 8, 9],
       [0, 0, 1, 7],
       [2, 4, 6, 9]])

In [35]:
np.sort(a)[::-1] #역순으로 보려했지만 차원이 안 맞아 제대로 안나옴

array([[2, 4, 6, 9],
       [0, 0, 1, 7],
       [5, 5, 8, 9]])

In [36]:
np.sort(a)[:,::-1] #행 그대로, 행 안의 열을 기준으로 역순정렬

array([[9, 8, 5, 5],
       [7, 1, 0, 0],
       [9, 6, 4, 2]])

In [37]:
# 열끼리 정렬할때 axis=0
np.sort(a,axis=0)

array([[0, 0, 1, 4],
       [5, 8, 2, 5],
       [6, 9, 9, 7]])

In [38]:
np.sort(a,axis=0)[::-1,:] #역순으로

array([[6, 9, 9, 7],
       [5, 8, 2, 5],
       [0, 0, 1, 4]])

## np.argsort(a,axis=-1,kind,order)
지정된 축으로 정렬할 인덱스 순서 반환

In [39]:
np.random.seed(1)
a=np.random.randint(0,10,12).reshape(3,4)
a

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [44]:
a

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [45]:
np.argsort(a) #정렬 후 원래 인덱스값 반환
# 5-8-9-5 원래값
# 5-5-8-9 정렬 후
# 0-3-1-2 각 값들의 원래 인덱스 값

array([[0, 3, 1, 2],
       [0, 1, 2, 3],
       [2, 3, 0, 1]], dtype=int64)

In [46]:
np.argsort(a)[:,::-1] #역순으로

array([[2, 1, 3, 0],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

In [47]:
# 열끼리 정렬
np.argsort(a,axis=0)

array([[1, 1, 1, 2],
       [0, 0, 2, 0],
       [2, 2, 0, 1]], dtype=int64)

In [48]:
np.argsort(a,axis=0)[::-1,:] #역순

array([[2, 2, 0, 1],
       [0, 0, 2, 0],
       [1, 1, 1, 2]], dtype=int64)

# 3. 배열 붙이기
np.concatenate

In [52]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b)) #튜플형태나 리스트 형태

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.concatenate([a,b]) #리스트 형태도 가능

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
x.shape, y.shape

((2, 2), (1, 2))

In [56]:
np.concatenate([x,y],axis=0) #axis=0은 열의 형태로 밑으로 쌓음

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
z=np.array([[5,6],[7,8]])
np.concatenate([x,z],axis=1)  #행을 이어붙여 옆으로 쌓음

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 4.배열 크기 구하기

In [58]:
arr=np.array([[[0,1,2,3],[4,5,6,7]],
             [[0,1,2,3],[4,5,6,7]],
             [[0,1,2,3],[4,5,6,7]]])
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [60]:
arr.ndim #차원-앞[[[의 개수->3차원

3

In [61]:
arr.size #요소 전체 개수

24

# shape
(a,b,c,d)->c행 d열 b개가 a개

In [62]:
arr.shape #형태->(3,2,4)->3개의 2행 4열

(3, 2, 4)

## reshape

In [63]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
np.reshape(a,newshape=(3,2),order='c') # order에는 C,F,A가능

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a=np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b=np.arange(24).reshape(2,3,4) #3차원
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
# 인덱싱
b[0,1,2] #첫번째 층에 2행 3열

6

In [12]:
c=np.arange(24).reshape(4,3,2,1) #4차원->2행1열 짜리 3개가 4묶음
c, c.shape

(array([[[[ 0],
          [ 1]],
 
         [[ 2],
          [ 3]],
 
         [[ 4],
          [ 5]]],
 
 
        [[[ 6],
          [ 7]],
 
         [[ 8],
          [ 9]],
 
         [[10],
          [11]]],
 
 
        [[[12],
          [13]],
 
         [[14],
          [15]],
 
         [[16],
          [17]]],
 
 
        [[[18],
          [19]],
 
         [[20],
          [21]],
 
         [[22],
          [23]]]]),
 (4, 3, 2, 1))

# 5.배열 확장or 축 추가

## np.newaxis

In [6]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [68]:
a.shape #1차원

(6,)

In [70]:
a2=a[np.newaxis,:] #행에 새로운 축, 나머지 6개전부를 열로
a2, a2.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [71]:
a3=a[:,np.newaxis] #6개 전부를 행으로, 열에 새로운 축
a3, a3.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 (6, 1))

In [8]:
a4=a[:,np.newaxis,np.newaxis]
a4, a4.shape

(array([[[1]],
 
        [[2]],
 
        [[3]],
 
        [[4]],
 
        [[5]],
 
        [[6]]]),
 (6, 1, 1))

In [9]:
a5=a[np.newaxis,np.newaxis,:]
a5, a5.shape

(array([[[1, 2, 3, 4, 5, 6]]]), (1, 1, 6))

In [27]:
aa=np.range(6).reshape(2,3)
aa2=aa[np.newaxis,:]   #이렇게 하면 에러
aa2

AttributeError: module 'numpy' has no attribute 'range'

## np.expand_dims()

In [18]:
a=np.array([1,2,3,4,5,6])
a, a.ndim, a.shape

(array([1, 2, 3, 4, 5, 6]), 1, (6,))

In [19]:
b=np.expand_dims(a,axis=1) #열로
b, b.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 (6, 1))

In [20]:
b=np.expand_dims(a,axis=0) #행으로
b, b.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [28]:
a=np.arange(6).reshape(2,3)
b=np.expand_dims(a,axis=2)  #2차원에서 axis=0,1,2 3개 가능->3차원으로
a,b,b.shape, b.ndim

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[[0],
         [1],
         [2]],
 
        [[3],
         [4],
         [5]]]),
 (2, 3, 1),
 3)