# 1.인덱싱과 슬라이싱

## 1차원 인덱싱
[]

In [1]:
import numpy as np

In [2]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [3]:
data[0]

1

In [4]:
data[2]

3

In [5]:
data[:2]

array([1, 2])

In [8]:
data[-1] #뒤에서부터

3

In [10]:
data[-2:] # -2에서부터 끝까지

array([2, 3])

In [12]:
data[-3:]

array([1, 2, 3])

## 2차원 인덱싱
[ , ] or [][]

In [13]:
data=np.arange(25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
data[2][1] #3행의 두번째 열

11

In [14]:
data[0,3:5] #0행의 3~(5-1)열

array([3, 4])

In [15]:
data[:,2]

array([ 2,  7, 12, 17, 22])

In [17]:
data[3:,3:]

array([[18, 19],
       [23, 24]])

In [19]:
data[2::2,::2] #2간격으로

array([[10, 12, 14],
       [20, 22, 24]])

In [26]:
data[[0,1,2],[0,1,2]] #각 각 하나씩

array([ 0,  6, 12])

In [23]:
data[(0,1,2),(0,1,2)] #튜플로도 가능

array([ 0,  6, 12])

In [38]:
data[[0,1,2],[2]] #크기 달라도 하나가 1개면 그 줄을 가져옴

array([ 2,  7, 12])

In [39]:
data[[0,1,2],[2,3]] #이렇게 하면 error->각 각 크기가 안맞아서->2:4로 해줘야함

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [27]:
# :로 하면 전부 가져옴
data[:3,[0,1,2]] 

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [29]:
data[[0,1,2],:3] #마찬가지

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [41]:
# T, F이용
mask=np.array([1,0,1,0,0],dtype=bool) #1이면 T, 0이면 F 
data[mask,2]

array([ 2, 12])

## 조건에 따른 인덱싱

In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [44]:
a[a<5]

array([1, 2, 3, 4])

In [45]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [47]:
a[(a>2)&(a<11)] #()하고 &=and

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a[(a>5)|(a==5)] # |는 or

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
a[a[:,0]>4,2:4] #1열 중 4보다 큰값이 있는 행에서 2,3열 가져오기

array([[ 7,  8],
       [11, 12]])

In [55]:
a[a[:,0]>4,[0,1,2]] #이렇게 하면 error->:3으로

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

### np.nonzero()
조건에 해당되는 인덱스값 반환

In [56]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
b=np.nonzero(a<5)
b #각 0행에 따른 0,1,2,3열 ->총 4개 요소가 a<5를 만족하고 각 인덱스를 반환

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [61]:
#위에꺼를 표현할때
lists=list(zip(b[0],b[1]))
lists

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [62]:
a[b]

array([1, 2, 3, 4])

# 2.기존 데이터를 사용한 배열 생성

## np.vstack() 밑으로 붙이기

In [63]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [64]:
np.vstack([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## np.hstack() 옆으로 붙이기

In [65]:
np.hstack([a1,a2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## np.hsplit() 만들어진 배열 쪼개기

In [67]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.hsplit(x,3) #옆으로 3개 만듬

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
np.hsplit(x,(2,4,6)) #튜플로 하면 2번 인덱스에서 끊고 4번 인덱스에서 끊고 6번 인덱스에서 끊음

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [72]:
np.hsplit(x,(1,4,7,9,10))

[array([[ 1],
        [13]]),
 array([[ 2,  3,  4],
        [14, 15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9],
        [20, 21]]),
 array([[10],
        [22]]),
 array([[11, 12],
        [23, 24]])]

## np.vsplit()

In [74]:
x=x.reshape(12,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [76]:
np.vsplit(x,3) #밑에 방향으로 3개 나눠지게끔

[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]),
 array([[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]])]

In [78]:
np.vsplit(x,(3,5,7,9)) #각 인덱스에서 끊어줌

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10]]),
 array([[11, 12],
        [13, 14]]),
 array([[15, 16],
        [17, 18]]),
 array([[19, 20],
        [21, 22],
        [23, 24]])]

## 배열에서 복사의 신기한 특징->얕은 복사

In [80]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [85]:
b=a[0,:] #b를 a로 부터 만듬 by 얕은 복사
b

array([99,  2,  3,  4])

In [83]:
b[0]=99
b

array([99,  2,  3,  4])

In [84]:
a #b에서 바꾼게 a에도 적용

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
#이를 방지하고자 .copy() 함수 사용->깊은 복사
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b2=a[0,:].copy()
b2

array([1, 2, 3, 4])

In [87]:
b2[0]=99
b2

array([99,  2,  3,  4])

In [88]:
a #안바뀜

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3. 배열의 산술연산
두 배열의 크기가 같아야하며 R처럼 배수로 계산 불가

In [90]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones #각 위치끼리 계산

array([2, 3])

In [91]:
data-ones, data*data, data/data

(array([0, 1]), array([1, 4]), array([1., 1.]))

## 함수사용

In [98]:
a=np.array([1,2,3,4]) # 1 차원
a.sum()

10

In [99]:
b=np.array([[1,1],[2,2]]) #2차원
b.sum(axis=0) #밑에 방향으로

array([3, 3])

In [100]:
b.sum(axis=1) #옆 방향으로

array([2, 4])

In [101]:
b.sum() #전체

6

# 4.broadcasting-다른 크기여도 연산 가능

## 배열과 스칼라의 연산

In [103]:
data = np.array([1.0, 2.0])
data * 1.6 #얘가 [1.6,1.6]형태가 되는 구조

array([1.6, 3.2])

In [113]:
data2=np.arange(12).reshape(3,4)
data2+1  #가능

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2D와 1D의 계산
(a X b)+ (c)에서 b와 c가 같아야함

In [114]:
dd=np.arange(12).reshape(3,4)
d=np.array([1,2,3,4])
dd.shape,d.shape

((3, 4), (4,))

In [115]:
dd+d #가능-> d를 믿으로 늘린 느낌

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [116]:
d2=np.array([1,2,3,4]).reshape(4,1)
dd+d2  # d2가 1행이라도 2차원이 된 순간 불가

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [118]:
d3=np.array([1,2,3])
dd+d3 #불가 

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [122]:
d4=np.array([1,2])
dd+d4 #배수 관계여도 R처럼 안됨

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

## 2D와 2D연산에서 하나의 2D가 (1 X a)형태 이면 가능

In [143]:
dd2=np.array([[1,10,100,1000]])
dd+dd2

array([[   1,   11,  102, 1003],
       [   5,   15,  106, 1007],
       [   9,   19,  110, 1011]])

In [145]:
dd2+dd #순서 바꿔도 가능

array([[   1,   11,  102, 1003],
       [   5,   15,  106, 1007],
       [   9,   19,  110, 1011]])

## 1D간의 크기 다른 연산은 앞에껄 축 확장

In [129]:
a=np.array([0,10,20,30])
b=np.array([1,2,3])
a[:,np.newaxis]+b #a를 np.newaxis로 옆으로 늘리면 가능, 각 a값은 행이 아닌 열로

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# 5. 1D, 2D에서 함수 사용

https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-ndarray-methods  
쓸수있는 함수들 목록

In [130]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [137]:
a.max(), a.min(), a.sum(), a.mean(), a.prod(), a.std(),a.var() #prod->전부 곱하기, std->표준편차, var->분산

(0.82485143,
 0.05093587,
 4.8595784,
 0.4049648666666667,
 1.4517216120884712e-06,
 0.21392120766089617,
 0.04576228308709627)

In [138]:
a.prod(axis=0),a.std(axis=0) #밑으로(각 열을 그룹으로)

(array([0.03125066, 0.00726716, 0.03662519, 0.17453384]),
 array([0.1794018 , 0.33973673, 0.05524104, 0.00759016]))

In [139]:
a.prod(axis=1),a.std(axis=1) #옆으로(각 행을 그룹으로)

(array([0.01476228, 0.00620385, 0.01585143]),
 array([0.14001164, 0.2044509 , 0.27060466]))