# 1.넘파이
행렬이나 다차원 배열 연산

## 넘파이 없이 리스트 전체에 10곱하기

In [1]:
data=[1,2,3,4]
result=[]
for i in data:
    result.append(i*10)
result

[10, 20, 30, 40]

## 넘파이의 array사용

In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4])
arr=arr*10
print(arr)
print(type(arr)) #ndarray

[10 20 30 40]
<class 'numpy.ndarray'>


## 2차원 데이터

In [2]:
price=[
    [100,80,70,90],
    [120,110,100,110]
]
price[0] #1번째 열인 100과 120을 뽑고싶지만 안됨

[100, 80, 70, 90]

In [3]:
arr2=np.array(price)
print(arr2[0]) #1번째 행
print(arr2[:,0]) #[x,y]로 원하는 행,열 가져오기 가능

[100  80  70  90]
[100 120]


In [5]:
arr2[:,[0,1]] #행렬로 나옴

array([[100,  80],
       [120, 110]])

## arange
파이썬의 range()

In [13]:
arr3=np.arange(10) #0~10-1까지
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr4=np.arange(1,10) #1~10-1까지
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x=np.arange(10).reshape(5,2) #5행 2열로
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 함수 적용

In [17]:
arr

array([10, 20, 30, 40])

In [18]:
arr.sum()

100

In [21]:
x.sum() #전부

45

In [25]:
print(x.sum(axis=0)) #같은 열끼리
print(x.sum(axis=1)) #같은 행끼리
print(x.sum(axis=None)) #전체 데이터

[20 25]
[ 1  5  9 13 17]
45


## random숫자 만들기

In [33]:
np.random.randint(3) #0~3-1숫자중 한개

1

In [34]:
np.random.randint(46, size=5) #0~45중 5개

array([31, 28, 41, 10, 20])

In [35]:
np.random.randint(46, size=(2, 5)) #2행 5열 행렬로

array([[25, 15, 29, 12,  1],
       [42, 42,  5, 28, 20]])

# linspace=range(a,b,c)

In [36]:
x = np.linspace(0, 10, 3) #0~10까지에서 균등하게 3등분
print(x)

[ 0.  5. 10.]


## stack함수
bind하여 행렬만들기

In [40]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.vstack( [a, b]) #수직방향으로=a밑에b쌓음
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.hstack( [a, b]) #수평방향으로=a옆에b
c

array([0, 1, 2, 3, 4, 5, 6, 7])