# 1. 넘파이
벡터화된 코드는 간결하고 읽기 쉽다.  
코드 줄 수가 적어 버그가 적다

In [1]:
import numpy as np

In [3]:
x=np.arange(15).reshape(3,5) #0~14까지 3행 5열로(row방향 우선으로)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
x.shape # dim

(3, 5)

## 인덱싱

In [7]:
x[:,:] #행, 열 전체

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
x[1:,::2] # 추가적인 :는 2번 건너뛴다-> 0,2,4열 뽑기

array([[ 5,  7,  9],
       [10, 12, 14]])

## 요소 변경

In [10]:
x[1:,::2]=-99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

## 함수사용

In [12]:
x.max() #최대값

13

In [13]:
x.max(axis=1) #행

array([ 4,  8, 13])

In [14]:
x.max(axis=0) #열 중

array([ 0, 11,  2, 13,  4])

In [17]:
x[1:,::2].max(axis=0) #인덱싱 후 함수사용 가능

array([-99, -99, -99])

## 정규분포 만들기

In [18]:
# 정규분포 수들 만들기
rng=np.random.default_rng()
samples=rng.normal(size=2500)
samples

array([ 0.21152867,  0.79930082, -0.84835314, ..., -0.23568154,
        1.86739823,  0.61774861])

In [19]:
len(samples)

2500

## 벡터간 연산

In [21]:
a=np.arange(5)
b=np.arange(5,10)
print(a*b,a+b,a-b,a/b)

[ 0  6 14 24 36] [ 5  7  9 11 13] [-5 -5 -5 -5 -5] [0.         0.16666667 0.28571429 0.375      0.44444444]
